// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2NeAb2qK1La4vCgNhQ1YqGsf8TYVXU8',
    appId: '1:661721676612:web:17831c8a2a0a08f87eb511',
    messagingSenderId: '661721676612',
    projectId: 'adet-exler',
    authDomain: 'adet-exler.firebaseapp.com',
    storageBucket: 'adet-exler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEU4qsNnWFD40Izc-i-7ABPaP7C-SLNQ',
    appId: '1:661721676612:android:4028619439104f387eb511',
    messagingSenderId: '661721676612',
    projectId: 'adet-exler',
    storageBucket: 'adet-exler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-aXCkLHu4L0YkSTOLt-TzflP8MWNbs0',
    appId: '1:661721676612:ios:d4fabf9a58df4ad37eb511',
    messagingSenderId: '661721676612',
    projectId: 'adet-exler',
    storageBucket: 'adet-exler.firebasestorage.app',
    iosBundleId: 'com.example.exler',
  );
}
